### PR TITLE
Bump to version 0.996

### PR DESCRIPTION
**Pull request by cmangla**

### CODE REVIEW

**Comment by cmangla** [comment]
@mre Is this all I need to merge to generate the release?

**Comment by mre** [comment]
That's the first step, yes. After that you'll have to go to the releases page and [draft a new release](https://github.com/mre/timelapse/releases/new).

The tag should be 

```
v0.996 @ Target: master
```

Release title should be `Version 0.996`.
Please also add a short release description.
I'd also tick the box for `This is a pre-release` for now as long as we're in "pre-1.0 stage".
That's it.

Theoretically you can do all that from the commandline as well since Github Releases is just a fancy UI around git tags, but I find it more convenient to do it from the release page.

**Comment by cmangla** [comment]
@mre All done, thanks for the instructions!

**Comment by mre** [comment]
Congrats! If you've got nothing else from your side, we could release 1.0 now. 🎉 
See #38.

**Pull request merged**
