### PR TITLE
Add test directory and Recorder class inclusive of 4 unit tests

### PR DESCRIPTION
**Pull request by ShaneCreedon**
I just added a test directory to work from as well as 4 unit tests revolving around the Recorder class.

### CODE REVIEW

**Comment by mre** [comment]
Great work. Could you move the tests to `tests/test_recorder.py`? (We added this structure yesterday.)

**Comment by mre** [comment]
```
tests/test_recorder.py:5: in <module>
    from recorder import Recorder
E   ModuleNotFoundError: No module named 'recorder'
```
😅

**Comment by mre** [comment]
I don't know what to do here. Maybe `from timelapse.recorder import Recorder`?

**Comment by ShaneCreedon** [comment]
Should be good now,  my bad.

**Comment by ShaneCreedon** [comment]
Build still seems to be failing, I'll look into it

**Comment by mre** [comment]
I moved the code into its own subfolder named `timelapse` and that did the trick. This is a best practice according to [the docs](https://docs.pytest.org/en/latest/goodpractices.html). Your original commits are part of the rollup in #15.
Would you be okay with merging #15 and closing this one? (Note: This still counts as a contribution to Hacktoberfest of course, if that is interesting to you. 😉)

**Comment by ShaneCreedon** [comment]
It is for Hacktoberfest yup and gladly! I'll merge and close once I get home.

**Pull request closed without merging**
