### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by mre**
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [X] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Update the versions of all packages
* Slightly improve check for ffmpeg

## Checklist

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by cmangla** [comment]
Here is my requirements.txt, attached. I just installed the latest versions. Worked fine for me.
[requirements.txt](https://github.com/mre/timelapse/files/3854817/requirements.txt)

**Comment by mre** [comment]
Thanks @cmangla. Yeah I was struggling with pip for a bit. Should have remembered that you posted the command to get the latest versions in your previous issue; but I didn't. 😆 
Anyway, the build still breaks. Let's see why...

**Comment by mre** [comment]
Yeah, the tests break. Should have covered that in my last review, heh. Let's see if I can fix it.

**Comment by cmangla** [comment]
> Yeah, the tests break. Should have covered that in my last review, heh. Let's see if I can fix it.

Sorry, my fault. `isSet` needs to be changed to `is_set`.

**Comment by mre** [comment]
Perfect. That fixed it. Can't add you as a reviewer, because you were not a collaborator. Sent you an invite link to fix that. 😉

**Comment by mre** [comment]
Thanks. Yeah I'm using Vim; removed now. 🤦‍♂ Thankfully there is a squash functionality in git...

**Comment by mre** [comment]
Cool. Thanks for the review.

**Pull request merged**
